version: '3.8'

volumes:
  db-store:
networks:
  network-app:
    driver: bridge

services:
  db:
    container_name: db-app
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: app          # Đổi MARIADB_ROOT_PASSWORD thành MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: db_app            # Đổi MARIADB_DATABASE thành MYSQL_DATABASE
      MYSQL_USER: app_user              # Tạo một user khác root để tránh cảnh báo của MySQL
      MYSQL_PASSWORD: app               # Đổi MARIADB_PASSWORD thành MYSQL_PASSWORD
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - db-store:/var/lib/mysql
    networks:
      - network-app
  app:
    container_name: bookapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - network-app
    environment:
      DB_HOST: db                       # Đổi MARIADB_HOST thành DB_HOST
      DB_PORT: 3306
      DB_DATABASE: db_app               # Đổi MARIADB_DATABASE thành DB_DATABASE
      DB_USERNAME: app_user             # Đổi MARIADB_USER thành DB_USERNAME
      DB_PASSWORD: app                  # Đổi MARIADB_PASSWORD thành DB_PASSWORD
  nginx:
    container_name: nginx-service
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9001:80
    networks:
      - network-app
    depends_on:
      - app
  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 91:80
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
    networks:
      - network-app